version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   # Persist database data
    networks:
      - flasknet

  flask-app:
    build:              # Build from your Dockerfile in the current directory
      context: ..
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb    # So Flask connects to MongoDB by container name
      - MONGO_PORT=27017
      - FLASK_ENV=development
    depends_on:
      - mongodb
    networks:
      - flasknet

networks:
  flasknet:
    name: flasknet            # Use same custom network name you created before

volumes:
  mongo_data:                 # Named volume to persist MongoDB data