name: flask_app
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - FLAKS_ENV=development
    volumes:
      - .:/app
    ports:
      - "5000:5000" # for flask port

volumes:
  mongo_data: