apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1  
  selector:
    matchLabels:
      app: to-do
  template:
    metadata:
      labels:
        app: to-do
    spec:
      containers:
        - name: to-do
          image: majiny/flask-app:v2
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: FLASK_ENV
              value: development
          imagePullPolicy: IfNotPresent

          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10 
            periodSeconds: 15    
            failureThreshold: 3      
          
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5  
            periodSeconds: 10
            failureThreshold: 3